/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#0c0f10",
        "inverse-primary": "#acaffd",
        "error-dim": "#770326",
        "inverse-on-surface": "#9b9d9e",
        "surface": "#f8f9fa",
        "primary-fixed-dim": "#a9adfa",
        "error": "#ac3149",
        "on-surface": "#2e3335",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#4e6365",
        "on-primary-fixed-variant": "#3b3e83",
        "on-secondary-container": "#4d5461",
        "on-secondary": "#f8f8ff",
        "tertiary-container": "#cae1e4",
        "on-tertiary-fixed": "#2b3f42",
        "surface-container": "#ebeef0",
        "on-tertiary-container": "#3d5255",
        "surface-bright": "#f8f9fa",
        "primary-container": "#b9bbff",
        "on-tertiary": "#e9fdff",
        "primary-dim": "#494c92",
        "tertiary-fixed-dim": "#bcd3d6",
        "surface-container-highest": "#dee3e5",
        "primary": "#55589f",
        "tertiary-dim": "#425759",
        "surface-variant": "#dee3e5",
        "on-secondary-fixed-variant": "#565e6b",
        "surface-dim": "#d5dbdd",
        "tertiary-fixed": "#cae1e4",
        "surface-container-low": "#f2f4f5",
        "secondary-container": "#dfe5f6",
        "secondary-dim": "#4c5361",
        "on-surface-variant": "#5a6062",
        "background": "#f8f9fa",
        "secondary-fixed": "#dfe5f6",
        "on-primary": "#fbf7ff",
        "on-secondary-fixed": "#3a414e",
        "on-primary-container": "#31357a",
        "secondary-fixed-dim": "#d1d7e7",
        "secondary": "#585f6d",
        "error-container": "#f76a80",
        "on-error-container": "#68001f",
        "on-primary-fixed": "#1b1e64",
        "on-tertiary-fixed-variant": "#475b5e",
        "outline-variant": "#aeb3b5",
        "on-background": "#2e3335",
        "primary-fixed": "#b9bbff",
        "outline": "#767c7e",
        "surface-container-high": "#e5e9eb",
        "surface-tint": "#55589f",
        "on-error": "#fff7f7",
        giet: {
          navy: '#272A6F',
          gold: '#EFBE33',
        }
      },
      boxShadow: {
        'ambient': '0px 12px 32px rgba(39, 42, 111, 0.06)',
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
}
